"""Create constraints table

Revision ID: 265e92e20f87
Revises: 594b128b6980
Create Date: 2026-03-23 23:01:22.708502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265e92e20f87'
down_revision = '594b128b6980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constraints')
    # ### end Alembic commands ###
